"""Spoticlaw package."""

from .spoticlaw import (
    SpotifyException,
    user,
    library,
    playlists,
    user_playlists,
    player,
    search,
    tracks,
    artists,
    albums,
    shows,
    episodes,
    follow,
    personalisation,
    memory_add_song,
    memory_set_feedback,
    discover_similar_artists,
    discover_similar_tracks,
    discover_similar_genres,
    get_history_genres,
    discover_from_history,
)

__all__ = [
    "SpotifyException",
    "user",
    "library",
    "playlists",
    "user_playlists",
    "player",
    "search",
    "tracks",
    "artists",
    "albums",
    "shows",
    "episodes",
    "follow",
    "personalisation",
    "memory_add_song",
    "memory_set_feedback",
    "discover_similar_artists",
    "discover_similar_tracks",
    "discover_similar_genres",
    "get_history_genres",
    "discover_from_history",
]
